language: java
script:
  - mvn javadoc:jar
  - mvn install
before_deploy:
  - mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
  - export project_version=$(mvn help:evaluate -N -Dexpression=project.version|grep -v '\[')
  - sed -i "s/\$PROJECT_VERSION/$project_version/g" .bintray.json
deploy:
  provider: bintray
  file: .bintray.json
  user: $BINTRAY_USERNAME
  key:
    secure: $BINTRAY_API_KEY
  skip_cleanup: true 
